# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: modelnet.yaml # choose the datamodule for evaluation
  - model: mvt.yaml
  - callbacks: null
  - logger: null
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: null

name: "default"

# passing checkpoint path is necessary
ckpt_path: /tmp/mvt/logs/experiments/runs/training/2022-07-25_17-30-59/tensorboard/tb_logger/training/checkpoints/epoch=22-step=2852.ckpt
